@extends('layouts.app-master')
@section('title', 'Auditoría')
@section('eyebrow', 'Gobierno y cumplimiento')
@section('page-title', 'Bitácora de auditoría')
@section('content')
    <div class="page-heading"><div><h2>Trazabilidad de cambios</h2><p>Registro inmutable de acciones administrativas con actor, contexto y momento de ejecución.</p></div></div>
    <form class="filter-bar filter-bar-compact" method="GET" action="{{ route('audit.index') }}"><select class="select" name="event"><option value="">Todos los eventos</option>@foreach(['employee.created','employee.updated','employee.archived','department.created','department.updated','department.deleted','leave.requested','leave.approved','leave.rejected','onboarding.created','onboarding.updated','goal.created','goal.progressed','deliverable.submitted','deliverable.approved','deliverable.rejected'] as $event)<option value="{{ $event }}" @selected(request('event') === $event)>{{ __('events.'.$event) }}</option>@endforeach</select><button class="button button-secondary" type="submit">Filtrar</button></form>
    <section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Actor</th><th>Evento</th><th>Origen</th><th>Registro</th></tr></thead><tbody>@forelse($logs as $log)<tr><td><time datetime="{{ $log->created_at->toIso8601String() }}">{{ $log->created_at->translatedFormat('d M Y · H:i') }}</time></td><td><span class="person"><span class="avatar">{{ mb_strtoupper(mb_substr($log->actor_name, 0, 2)) }}</span><span><strong>{{ $log->actor_name }}</strong><small>{{ ucfirst($log->actor_type) }}</small></span></span></td><td>{{ __('events.'.$log->event) }}</td><td><span class="subtle">{{ $log->ip_address ?: 'No disponible' }}</span></td><td><span class="subtle">#{{ $log->auditable_id }}</span></td></tr>@empty<tr><td colspan="5"><div class="empty-state"><strong>No hay actividad registrada</strong>Los cambios administrativos aparecerán aquí.</div></td></tr>@endforelse</tbody></table></div>@include('layouts.partials.pagination', ['paginator' => $logs])</section>
@endsection
